name: evento_shell
description: White-label Flutter app shell for Evento events

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  evento_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.12
  yaml: ^3.1.2
  path: ^1.9.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/generated/

dependency_overrides:
  mapbox_maps_flutter: 2.12.0-beta.1

