name: evento_core
description: base code for all different events app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.4.0+11

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  onesignal_flutter: ^5.2.5
  get: ^4.6.6
  shared_preferences: ^2.2.3
  responsive_sizer: ^3.3.1
  dio: ^5.5.0+1
  intl: ^0.19.0
  fluttertoast: ^8.2.6
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  cached_network_image: ^3.3.1
  package_info_plus: ^8.0.2
  path_provider: ^2.1.3
  flutter_feather_icons: ^2.0.0+1
  path: ^1.9.0
  connectivity_plus: ^6.0.4
  syncfusion_flutter_pdfviewer: ^24.2.8
  geojson:
    git:
      url: git@github.com:coding-master15/geojson.git
      ref: 92a14cd631d537a24a40a84b677a38c314beb723

  
  carousel_slider: ^5.0.0
  youtube_player_flutter: ^9.1.0
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  sqlite3_flutter_libs: ^0.5.24
  drift_sqflite: ^2.0.1
  drift: ^2.20.2
  collection: ^1.18.0
  webview_flutter: ^4.8.0
  flutter_svg: ^2.0.10+1
  # mobile_scanner: ^3.5.2
  pull_to_refresh: ^2.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geodart: ^0.3.6
  miniplayer: ^1.0.1
  smooth_page_indicator: ^1.1.0
  share_plus: ^7.2.1
  flutter_inappwebview: ^6.1.0+1
  video_player: ^2.8.2
  flutter_cache_manager: ^3.3.1
  app_links: ^6.3.2
  mapbox_maps_flutter: ^2.2.1
  screenshot: ^3.0.0
  geolocator: ^12.0.0
  geodesy: ^0.10.2
  fl_chart: ^0.68.0
  apple_maps_flutter: ^1.3.0
  get_storage:
  win32: ^5.5.4
  #new_version_plus: ^0.0.11


dependency_overrides:
  latlong2: ^0.9.0
  win32: ^5.5.4
  win32_registry: ^1.1.5
  geopoint:
    git:
      url: git@github.com:coding-master15/geopoint.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.12
  drift_dev: ^2.20.3
  mocktail: ^1.0.4

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"

flutter:
  uses-material-design: true

  assets:
    - packages/evento_core/assets/svgs/article.svg
    - packages/evento_core/assets/svgs/assignment.svg
    - packages/evento_core/assets/svgs/auto_stories.svg
    - packages/evento_core/assets/svgs/campaign.svg
    - packages/evento_core/assets/svgs/chevron_left.svg
    - packages/evento_core/assets/svgs/date_range.svg
    - packages/evento_core/assets/svgs/directions_bike.svg
    - packages/evento_core/assets/svgs/directions_run.svg
    - packages/evento_core/assets/svgs/done.svg
    - packages/evento_core/assets/svgs/event.svg
    - packages/evento_core/assets/svgs/filter_drama.svg
    - packages/evento_core/assets/svgs/gps_fixed.svg
    - packages/evento_core/assets/svgs/image.svg
    - packages/evento_core/assets/svgs/info.svg
    - packages/evento_core/assets/svgs/landscape.svg
    - packages/evento_core/assets/svgs/language.svg
    - packages/evento_core/assets/svgs/laptop.svg
    - packages/evento_core/assets/svgs/layers.svg
    - packages/evento_core/assets/svgs/list_numbered.svg
    - packages/evento_core/assets/svgs/list.svg
    - packages/evento_core/assets/svgs/location_searching.svg
    - packages/evento_core/assets/svgs/map.svg
    - packages/evento_core/assets/svgs/medical_services.svg
    - packages/evento_core/assets/svgs/menu_book.svg
    - packages/evento_core/assets/svgs/near_me.svg
    - packages/evento_core/assets/svgs/people.svg
    - packages/evento_core/assets/svgs/personal_video.svg
    - packages/evento_core/assets/svgs/phone.svg
    - packages/evento_core/assets/svgs/picture_as_pdf.svg
    - packages/evento_core/assets/svgs/qr_code.svg
    - packages/evento_core/assets/svgs/shopping_bag.svg
    - packages/evento_core/assets/svgs/sticky_note_2.svg
    - packages/evento_core/assets/svgs/subject.svg
    - packages/evento_core/assets/svgs/support_agent.svg
    - packages/evento_core/assets/svgs/terrain.svg
    - packages/evento_core/assets/svgs/text_snippet.svg
    - packages/evento_core/assets/svgs/trophey.svg
    - packages/evento_core/assets/svgs/verified_user.svg
    - packages/evento_core/assets/svgs/videocam.svg
    - packages/evento_core/assets/svgs/view_list.svg
    - packages/evento_core/assets/svgs/watch_later.svg
    - packages/evento_core/assets/svgs/wb_sunny.svg
    - packages/evento_core/assets/svgs/web.svg
    - packages/evento_core/assets/svgs/startingpoint.svg
    - packages/evento_core/assets/svgs/finishpoint.svg

    - packages/evento_core/assets/images/splash_image.png
    - packages/evento_core/assets/images/instagram.png
    - packages/evento_core/assets/images/general.png
    - packages/evento_core/assets/images/share.png
    - packages/evento_core/assets/images/speedometer.webp
    - packages/evento_core/assets/images/aidstation.png
    - packages/evento_core/assets/images/camera.png
    - packages/evento_core/assets/images/checkpoint.png
    - packages/evento_core/assets/images/bagdrop.png
    - packages/evento_core/assets/images/bus.png
    - packages/evento_core/assets/images/caution.png
    - packages/evento_core/assets/images/firstaid.png
    - packages/evento_core/assets/images/info.png
    - packages/evento_core/assets/images/mechanic.png
    - packages/evento_core/assets/images/parking.png
    - packages/evento_core/assets/images/roadclosure_marker.png
    - packages/evento_core/assets/images/timing.png
    - packages/evento_core/assets/images/wc.png
    - packages/evento_core/assets/images/waterpoint_marker.png
    - packages/evento_core/assets/images/turnaround.png
    - packages/evento_core/assets/images/spectators.png
    - packages/evento_core/assets/images/square.png
    - packages/evento_core/assets/images/square2.png
    - packages/evento_core/assets/images/square3.png
    - packages/evento_core/assets/images/trophy.png
    - packages/evento_core/assets/images/transparent.png

