name: evento_core
description: base code for all different events app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.4.0+11

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  onesignal_flutter: ^3.3.0
  get: ^4.6.1
  shared_preferences: ^2.0.13
  responsive_sizer: ^3.0.5+1
  dio: ^5.3.2
  intl: ^0.18.1
  fluttertoast: ^8.0.9
  permission_handler: ^10.2.0
  url_launcher: ^6.0.20
  cached_network_image: ^3.2.0
  package_info_plus: ^4.0.2
  path_provider: ^2.0.9
  flutter_feather_icons: ^2.0.0+1
  path: ^1.8.0
  connectivity_plus: ^4.0.2
  syncfusion_flutter_pdfviewer: ^20.4.54
  geojson: ^1.0.0
  latlong2: ^0.8.1
  carousel_slider: ^4.2.1
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_messaging: ^14.6.7
  sqlite3_flutter_libs: ^0.5.8
  drift_sqflite: ^2.0.1
  drift: ^2.11.1
  collection:
  webview_flutter: ^4.2.4
  flutter_svg: ^2.0.7
  flutter_map:
  video_player: ^2.4.7
  mobile_scanner: ^3.4.1
  pull_to_refresh: ^2.0.0
  flutter_flavorizr: ^2.2.1
  mapbox_maps_flutter: ^0.4.4
  bloc: ^8.1.2
  go_router: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.2.0
  drift_dev: ^2.11.1

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"

  flavors:
    flavordemo:
      app:
        name: "Evento Tracker"
      android:
        applicationId: "nz.netproject.eventotracker"
        customConfig:
          versionCode: 1
      ios:
        bundleId: "nz.netproject.eventotracker"

    eventodemo:
      app:
        name: "Evento Demo"
      android:
        applicationId: "nz.netproject.eventotracker.demo"
        firebase:
          config: "flavors/eventodemo/google-services.json"
        customConfig:
          versionCode: 91
      ios:
        bundleId: "nz.netproject.eventotracker.demo"
        firebase:
          config: "flavors/eventodemo/GoogleService-Info.plist"

    epicseries:
      app:
        name: "Epic Series"
        icon: "flavors/epicseries/ic_launcher.png"
      android:
        applicationId: "nz.netproject.mtbseries"
        firebase:
          config: "flavors/epicseries/google-services.json"
        customConfig:
          versionCode: 23
      ios:
        bundleId: "nz.netproject.mtbseries"
        firebase:
          config: "flavors/epicseries/GoogleService-Info.plist"

    motatapu:
      app:
        name: "Motatapu"
        icon: "flavors/motatapu/ic_launcher.png"
      android:
        applicationId: "nz.netproject.motatapu"
        firebase:
          config: "flavors/motatapu/google-services.json"
        customConfig:
          versionCode: 21
      ios:
        bundleId: "nz.netproject.motatapu"
        firebase:
          config: "flavors/motatapu/GoogleService-Info.plist"

    noosatri:
      app:
        name: "Noosatri"
        icon: "flavors/noosatri/ic_launcher.png"
      android:
        applicationId: "nz.netproject.noosatri"
        firebase:
          config: "flavors/noosatri/google-services.json"
        customConfig:
          versionCode: 22      
      ios:
        bundleId: "nz.netproject.noosatri"
        firebase:
          config: "flavors/noosatri/GoogleService-Info.plist"

    mootri:
      app:
        name: "Mootri"
        icon: "flavors/mootri/ic_launcher.png"
      android:
        applicationId: "nz.netproject.mootri"
        firebase:
          config: "flavors/mootri/google-services.json"
        customConfig:
          versionCode: 21
      ios:
        bundleId: "nz.netproject.mootri"
        firebase:
          config: "flavors/mootri/GoogleService-Info.plist"

    uta:
      app:
        name: "UTA"
        icon: "flavors/ultratrailaustralia/ic_launcher.png"
      android:
        applicationId: "nz.netproject.ultratrailaustralia"
        firebase:
          config: "flavors/ultratrailaustralia/google-services.json"
        customConfig:
          versionCode: 21
      ios:
        bundleId: "nz.netproject.ultratrailaustralia"
        firebase:
          config: "flavors/ultratrailaustralia/GoogleService-Info.plist"

    # kosci:
    #   app:
    #     name: "Kosci"
    #     icon: "flavors/ultratrailkosci/ic_launcher.png"
    #   android:
    #     applicationId: "nz.netproject.kosci"
    #     firebase:
    #       config: "flavors/ultratrailkosci/google-services.json"
    #     customConfig:
    #       versionCode: 3
    #   ios:
    #     bundleId: "nz.netproject.kosci"
    #     firebase:
    #       config: "flavors/ultratrailkosci/GoogleService-Info.plist"

    rtb:
      app:
        name: "Round the Bays"
        icon: "flavors/rtb/ic_launcher.png"
      android:
        applicationId: "nz.netproject.rtb"
        firebase:
          config: "flavors/rtb/google-services.json"
        customConfig:
          versionCode: 19
      
      ios:
        bundleId: "nz.netproject.rtb"
        firebase:
          config: "flavors/rtb/GoogleService-Info.plist"

    auckland:
      app:
        name: "AA Marathon"
        icon: "flavors/aamarathon/ic_launcher.png"
      android:
        applicationId: "nz.netproject.aamarathon"
        firebase:
          config: "flavors/aamarathon/google-services.json"
        customConfig:
          versionCode: 25
      ios:
        bundleId: "nz.netproject.aamarathon"
        firebase:
          config: "flavors/aamarathon/GoogleService-Info.plist"

    whaka100:
      app:
        name: "Whaka 100"
        icon: "flavors/whaka100/ic_launcher.png"
      android:
        applicationId: "nz.netproject.whaka100"
        firebase:
          config: "flavors/whaka100/google-services.json"
        customConfig:
          versionCode: 9
      ios:
        bundleId: "nz.netproject.whaka100"
        firebase:
          config: "flavors/whaka100/GoogleService-Info.plist"

    ironman:
      app:
        name: "IRONMAN"
        icon: "flavors/ironmanoceania/ic_launcher.png"
      android:
        applicationId: "nz.netproject.im_oceania"
        firebase:
          config: "flavors/ironmanoceania/google-services.json"
        customConfig:
          versionCode: 25
      ios:
        bundleId: "nz.netproject.im_oceania"
        firebase:
          config: "flavors/ironmanoceania/GoogleService-Info.plist"

    runaway:
      app:
        name: "Runaway"
        icon: "flavors/runaway/ic_launcher.png"
      android:
        applicationId: "nz.netproject.runaway"
        firebase:
          config: "flavors/runaway/google-services.json"
        customConfig:
          versionCode: 24
      ios:
        bundleId: "nz.netproject.runaway"
        firebase:
          config: "flavors/runaway/GoogleService-Info.plist"

    challenge:
      app:
        name: "Challenge Wanaka"
        icon: "flavors/challengewanaka/ic_launcher.png"
      android:
        applicationId: "nz.netproject.challengewanaka"
        firebase:
          config: "flavors/challengewanaka/google-services.json"
        customConfig:
          versionCode: 12
      ios:
        bundleId: "nz.netproject.challengewanaka"
        firebase:
          config: "flavors/challengewanaka/GoogleService-Info.plist"

    coasttocoast:
      app:
        name: "Coast To Coast"
        icon: "flavors/coasttocoast/ic_launcher.png"
      android:
        applicationId: "nz.netproject.coasttocoast"
        firebase:
          config: "flavors/coasttocoast/google-services.json"
        customConfig:
          versionCode: 23
      ios:
        bundleId: "nz.netproject.coasttocoast"
        firebase:
          config: "flavors/coasttocoast/GoogleService-Info.plist"

    chmarathon:
      app:
        name: "CH Marathon"
        icon: "flavors/chmarathon/ic_launcher.png"
      android:
        applicationId: "nz.netproject.chmarathon"
        firebase:
          config: "flavors/chmarathon/google-services.json"
        customConfig:
          versionCode: 1
      ios:
        bundleId: "nz.netproject.chmarathon"
        firebase:
          config: "flavors/chmarathon/GoogleService-Info.plist"

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/videos/
    - assets/images/