name: evento_core
description: base code for all different events app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.4.0+11

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  onesignal_flutter: ^3.3.0
  get: ^4.6.1
  shared_preferences: ^2.0.13
  responsive_sizer: ^3.0.5+1
  dio: ^5.3.2
  intl: ^0.18.1
  fluttertoast: ^8.0.9
  permission_handler: ^10.2.0
  url_launcher: ^6.0.20
  cached_network_image: ^3.2.0
  package_info_plus: ^4.0.2
  path_provider: ^2.0.9
  flutter_feather_icons: ^2.0.0+1
  path: ^1.8.0
  connectivity_plus: ^4.0.2
  syncfusion_flutter_pdfviewer:
  geojson: ^1.0.0
  carousel_slider: ^4.2.1
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_messaging: ^14.6.7
  sqlite3_flutter_libs: ^0.5.8
  drift_sqflite: ^2.0.1
  drift: ^2.11.1
  collection:
  webview_flutter: ^4.2.4
  flutter_svg: ^2.0.7
  video_player: ^2.4.7
  mobile_scanner: ^3.4.1
  pull_to_refresh: ^2.0.0
  flutter_map:
  latlong2:
  geodart: 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.2.0
  drift_dev: ^2.11.1

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/