name: evento_tracker
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  evento_core:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/